// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDScbo8zd5nKdroDyTZdaXEgAfFJf_7nUs',
    appId: '1:836113906302:web:65dd0f3eeaaa8498ee362f',
    messagingSenderId: '836113906302',
    projectId: 'restaurant-dc2c3',
    authDomain: 'restaurant-dc2c3.firebaseapp.com',
    storageBucket: 'restaurant-dc2c3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMmlZAWBKqsaFOSuaaOoNca_4qc5dfWqc',
    appId: '1:836113906302:android:3b644c35a83e20deee362f',
    messagingSenderId: '836113906302',
    projectId: 'restaurant-dc2c3',
    storageBucket: 'restaurant-dc2c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdLUMEW-hlvD4-Cj306BUKwm_-s27xVXY',
    appId: '1:836113906302:ios:7e030aebc8c6b25aee362f',
    messagingSenderId: '836113906302',
    projectId: 'restaurant-dc2c3',
    storageBucket: 'restaurant-dc2c3.appspot.com',
    iosBundleId: 'com.example.restauranteUlises',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdLUMEW-hlvD4-Cj306BUKwm_-s27xVXY',
    appId: '1:836113906302:ios:7e030aebc8c6b25aee362f',
    messagingSenderId: '836113906302',
    projectId: 'restaurant-dc2c3',
    storageBucket: 'restaurant-dc2c3.appspot.com',
    iosBundleId: 'com.example.restauranteUlises',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDScbo8zd5nKdroDyTZdaXEgAfFJf_7nUs',
    appId: '1:836113906302:web:af31790f7514828dee362f',
    messagingSenderId: '836113906302',
    projectId: 'restaurant-dc2c3',
    authDomain: 'restaurant-dc2c3.firebaseapp.com',
    storageBucket: 'restaurant-dc2c3.appspot.com',
  );
}